version: "1"

services:
  askmeanything_db:
    container_name: askmeanything_db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
      
  askmeanything_app:
    image: askmeanything:latest
    container_name: askmeanything_app
    build: .
    links:
      - askmeanything_db:db  # Link the app to the db service, creating an alias "db"
    ports:
      - "4000:4000"
    command: bash -c "alembic upgrade head && sleep 2 && gunicorn -b :4000 --access-logfile - --error-logfile - askMeAnything:app"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - askmeanything_db
    networks:
      - app-network

volumes:
  db_data: {}
 
networks:
  app-network:
